
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CYCLE DOS_P FN IDENTIFICADOR IGUAL INT LLAVE_D LLAVE_I OPERADOR PARENTESIS_D PARENTESIS_I PM PUNTO_Y_C RN SCREEN SO STRING TYPE VARIABLE WHENstart : structuresstructures : structures structure\n                  | structurestructure : var_decl\n                 | func_decl\n                 | cycle_decl\n                 | when_decl\n                 | statementvar_decl : VARIABLE DOS_P TYPE IGUAL value PUNTO_Y_Cfunc_decl : RN IDENTIFICADOR PARENTESIS_I PARENTESIS_D LLAVE_I statements LLAVE_Dcycle_decl : FN IDENTIFICADOR PARENTESIS_I PARENTESIS_D LLAVE_I CYCLE PARENTESIS_I var_decl condicion PUNTO_Y_C incremento PARENTESIS_D LLAVE_I statements LLAVE_D LLAVE_Dwhen_decl : FN IDENTIFICADOR PARENTESIS_I PARENTESIS_D LLAVE_I WHEN PARENTESIS_I condicion PARENTESIS_D LLAVE_I statements LLAVE_D so_decl LLAVE_Dso_decl : SO LLAVE_I statements LLAVE_Dstatements : statements statement\n                  | statementstatement : SCREEN PARENTESIS_I STRING PARENTESIS_D PUNTO_Y_C\n                 | SCREEN PARENTESIS_I IDENTIFICADOR PARENTESIS_D PUNTO_Y_Cvalue : INT\n             | STRING\n    condicion : IDENTIFICADOR OPERADOR value\n                 | IDENTIFICADOR OPERADOR IDENTIFICADOR\n                 | VARIABLE OPERADOR value\n    incremento : IDENTIFICADOR PM'
    
_lr_action_items = {'VARIABLE':([0,2,3,4,5,6,7,8,13,33,34,35,40,42,43,44,67,71,],[9,9,-3,-4,-5,-6,-7,-8,-2,-16,-17,-9,-10,9,47,47,-12,-11,]),'RN':([0,2,3,4,5,6,7,8,13,33,34,35,40,67,71,],[10,10,-3,-4,-5,-6,-7,-8,-2,-16,-17,-9,-10,-12,-11,]),'FN':([0,2,3,4,5,6,7,8,13,33,34,35,40,67,71,],[11,11,-3,-4,-5,-6,-7,-8,-2,-16,-17,-9,-10,-12,-11,]),'SCREEN':([0,2,3,4,5,6,7,8,13,31,33,34,35,36,37,40,41,55,59,63,66,67,68,70,71,],[12,12,-3,-4,-5,-6,-7,-8,-2,12,-16,-17,-9,12,-15,-10,-14,12,12,12,12,-12,12,12,-11,]),'$end':([1,2,3,4,5,6,7,8,13,33,34,35,40,67,71,],[0,-1,-3,-4,-5,-6,-7,-8,-2,-16,-17,-9,-10,-12,-11,]),'DOS_P':([9,],[14,]),'IDENTIFICADOR':([10,11,17,35,43,44,49,52,],[15,16,22,-9,45,45,53,57,]),'PARENTESIS_I':([12,15,16,38,39,],[17,19,20,42,43,]),'TYPE':([14,],[18,]),'STRING':([17,23,49,51,],[21,30,30,30,]),'IGUAL':([18,],[23,]),'PARENTESIS_D':([19,20,21,22,29,30,46,53,54,56,58,60,],[24,25,26,27,-18,-19,50,-21,-20,-22,61,-23,]),'INT':([23,49,51,],[29,29,29,]),'LLAVE_I':([24,25,50,61,65,],[31,32,55,63,68,]),'PUNTO_Y_C':([26,27,28,29,30,48,53,54,56,],[33,34,35,-18,-19,52,-21,-20,-22,]),'CYCLE':([32,],[38,]),'WHEN':([32,],[39,]),'LLAVE_D':([33,34,36,37,41,59,64,66,69,70,72,],[-16,-17,40,-15,-14,62,67,69,71,72,-13,]),'OPERADOR':([45,47,],[49,51,]),'PM':([57,],[60,]),'SO':([62,],[65,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'structures':([0,],[2,]),'structure':([0,2,],[3,13,]),'var_decl':([0,2,42,],[4,4,44,]),'func_decl':([0,2,],[5,5,]),'cycle_decl':([0,2,],[6,6,]),'when_decl':([0,2,],[7,7,]),'statement':([0,2,31,36,55,59,63,66,68,70,],[8,8,37,41,37,41,37,41,37,41,]),'value':([23,49,51,],[28,54,56,]),'statements':([31,55,63,68,],[36,59,66,70,]),'condicion':([43,44,],[46,48,]),'incremento':([52,],[58,]),'so_decl':([62,],[64,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> structures','start',1,'p_start','yacc.py',5),
  ('structures -> structures structure','structures',2,'p_structures','yacc.py',9),
  ('structures -> structure','structures',1,'p_structures','yacc.py',10),
  ('structure -> var_decl','structure',1,'p_structure','yacc.py',17),
  ('structure -> func_decl','structure',1,'p_structure','yacc.py',18),
  ('structure -> cycle_decl','structure',1,'p_structure','yacc.py',19),
  ('structure -> when_decl','structure',1,'p_structure','yacc.py',20),
  ('structure -> statement','structure',1,'p_structure','yacc.py',21),
  ('var_decl -> VARIABLE DOS_P TYPE IGUAL value PUNTO_Y_C','var_decl',6,'p_declaracion_variable','yacc.py',25),
  ('func_decl -> RN IDENTIFICADOR PARENTESIS_I PARENTESIS_D LLAVE_I statements LLAVE_D','func_decl',7,'p_funcion_declaracion','yacc.py',34),
  ('cycle_decl -> FN IDENTIFICADOR PARENTESIS_I PARENTESIS_D LLAVE_I CYCLE PARENTESIS_I var_decl condicion PUNTO_Y_C incremento PARENTESIS_D LLAVE_I statements LLAVE_D LLAVE_D','cycle_decl',16,'p_cycle_funcion','yacc.py',40),
  ('when_decl -> FN IDENTIFICADOR PARENTESIS_I PARENTESIS_D LLAVE_I WHEN PARENTESIS_I condicion PARENTESIS_D LLAVE_I statements LLAVE_D so_decl LLAVE_D','when_decl',14,'p_when_funcion','yacc.py',45),
  ('so_decl -> SO LLAVE_I statements LLAVE_D','so_decl',4,'p_so_decl','yacc.py',50),
  ('statements -> statements statement','statements',2,'p_statements','yacc.py',55),
  ('statements -> statement','statements',1,'p_statements','yacc.py',56),
  ('statement -> SCREEN PARENTESIS_I STRING PARENTESIS_D PUNTO_Y_C','statement',5,'p_impresion','yacc.py',63),
  ('statement -> SCREEN PARENTESIS_I IDENTIFICADOR PARENTESIS_D PUNTO_Y_C','statement',5,'p_impresion','yacc.py',64),
  ('value -> INT','value',1,'p_value','yacc.py',68),
  ('value -> STRING','value',1,'p_value','yacc.py',69),
  ('condicion -> IDENTIFICADOR OPERADOR value','condicion',3,'p_condicion','yacc.py',74),
  ('condicion -> IDENTIFICADOR OPERADOR IDENTIFICADOR','condicion',3,'p_condicion','yacc.py',75),
  ('condicion -> VARIABLE OPERADOR value','condicion',3,'p_condicion','yacc.py',76),
  ('incremento -> IDENTIFICADOR PM','incremento',2,'p_incremento','yacc.py',81),
]
